nhom_10/KienBD-Nhom10-ShoppingCartOnline/sample_app/config/routes.rb
SampleApp::Application.routes.draw do

  post "users/find"
  match '/users/:name', to: 'users#search', name: /\d*[a-z]+\d*[a-z]+\d*/i
  match '/create' , to:  'users#create',via: :post
  resources :users
  resources :categories
  resources :products
  resources :items
  resources :cart
  resources :sessions, only: [:new,:create,:destroy]

  root to: 'static_pages#home'
  match '/search',  to: 'static_pages#search'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

nhom_10/KienBD-Nhom10-ShoppingCartOnline/sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

nhom_10/KienBD-Nhom10-ShoppingCartOnline/sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Shoping Cart", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <%# <form class="navbar-search pull-left" action="/users/find" method="post"> %>
            <%# <input type="text" class="search-query" name="email" placeholder="Search"> %>
          <%# </form> %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in?  %>
            <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <%end%>
          <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Shop <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Categories", categories_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Products", products_path %></li>
          </ul>
          </li>
          <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          </ul>
          </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

nhom_10/KienBD-Nhom10-ShoppingCartOnline/sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

nhom_10/KienBD-Nhom10-ShoppingCartOnline/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>