nhom_11/DAO_DUC_TUNG/config/routes.rb
SampleApp::Application.routes.draw do
  root to: "products#index"

  match "/help", to: "static_pages#help"
  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/checkout', to: 'orders#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :products
  resources :cart_items, only: [:index, :create, :destroy]
  resources :orders
end

nhom_11/DAO_DUC_TUNG/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :products
end

nhom_11/DAO_DUC_TUNG/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :admin_user, only: [:create, :destroy, :edit]

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page])
  end

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:success] = "Category added"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:success] = "Category updated"
      redirect_to categories_path
    else
      render 'edit'
    end
  end
end

nhom_11/DAO_DUC_TUNG/app/views/categories/_fields.html.erb
<%= render('shared/error_messages', object: f.object) %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "Save", class: "btn btn-primary btn-large" %>

nhom_11/DAO_DUC_TUNG/app/views/categories/edit.html.erb
<% provide(:title, 'Edit category') %>
<h1>Edit category</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@category) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Update", class: "btn btn-primary btn-large" %>
    <% end %>
  </div>
</div>

nhom_11/DAO_DUC_TUNG/app/views/categories/index.html.erb
<% provide(:title, 'All categories') -%>
<h1>Categories</h1>

<ul class="categories">
  <% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_path(cat) %>
    <% if !current_user.nil? && current_user.admin? %>
  | <%= link_to "Edit", edit_category_path(cat) %>
  | <%= link_to "Delete", cat, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= will_paginate %>

nhom_11/DAO_DUC_TUNG/app/views/categories/new.html.erb
<% provide(:title, 'Add new category') -%>
<h1>Add new category</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@category) do |f| %>
      <%= render 'fields', f: f %>
    <% end %>
  </div>
</div>

nhom_11/DAO_DUC_TUNG/app/views/categories/show.html.erb
<% provide(:title, @category.name) -%>
<h1><%= @category.name %></h1>

<div class="row">
  <% if !current_user.nil? && current_user.admin? %>
    <div class="span12">
      <table class="table table-bordered table-strip">
        <thead>
          <tr>
            <td>Name</td>
            <td>Price</td>
            <td>Description</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| -%>
            <tr>
              <td><%= link_to product.name, product %></td>
              <td><%= product.price %></td>
              <td><%= product.description %></td>
              <td>
                <%= link_to "Edit", edit_product_path(product)  %>
                <%= link_to "Delete", product, method: :delete, data: { confirm: "You sure?" } %>
            </td>
          </tr>
        <% end -%>
      </tbody>
    </table>
    <div class="span10 offset2"><%= will_paginate %></div>
  </div>
<% else %>
  <aside class="span2 alpha">
    <%= render 'shared/sidebar' %>
  </aside>
  <div class="span10" style="margin-left: 20px">
    <% @products.each do |product| -%>
      <div class="span3 well" style="max-width: 25%;">
        <%= render product %>
        <%= link_to "View", product %>
      </div>
    <% end -%>
  </div>
  <div class="span10 offset2"><%= will_paginate @products %></div>
<% end -%>
</div>